const actionTypes = {
   
    INITIATE_LOGIN: 'INITIATE_LOGIN',
    INITIATE_LOGIN_SUCCESS: 'INITIATE_LOGIN_SUCCESS',
    INITIATE_LOGIN_FAILURE: 'INITIATE_LOGIN_FAILURE',

    INITIATE_LOGIN_STATUS: 'INITIATE_LOGIN_STATUS',
    ALREADY_LOGGED_IN: 'ALREADY_LOGGED_IN',
    NOT_ALREADY_LOGGEDIN: 'NOT_ALREADY_LOGGEDIN'
};

export default actionTypes;